name: Build Branch
run-name: ${{ github.actor }} is testing out building with GitHub Actions 🚀
on: [push]
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: Dockerfile
                options: --privileged --user=root --entrypoint /bin/sh -v ${{ github.workspace }}:/src
                run: |
                    make build